name: My Computing Diary
description: "A self-documenting blog for hints, findings and tips of everyday computing"
meta_description: "A blog with everything related with Computing"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'anwarshah.github.io'
google_analytics: 'UA-71364561-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://anwarshah.github.io'
author:         'Anwar Shah'

theme:
  gravatar: d10030254a922e6d2ae120d04ae119ed

# Build settings. Found in SO to fix multi-categories
permalink: /:categories/:title/

gems:
  - jekyll-seo-tag